name = "battlesnake"
version = "0.1.0"

description = "A Gleam wrapper for the Battlesnake API"
licences = ["MIT"]
repository = { type = "github", user = "leah-u", repo = "battlesnake" }
links = [{ title = "Battlesnake Docs", href = "https://docs.battlesnake.com/" }]

gleam = ">= 1.4.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
